name: Grant Application CI

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugins
        run: dotnet build GM.Plugins/GM.Plugins.csproj --configuration Release --no-restore

      - name: Run plugin tests
        run: dotnet test GM.Plugin.Tests/GM.Plugin.Tests.csproj --configuration Release --no-build